# Generated by Django 3.2 on 2021-05-03 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ipo',
            fields=[
                ('company_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('max_price_band', models.IntegerField()),
                ('min_price_band', models.IntegerField()),
                ('price', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'ipo',
                'ordering': ['-company_code'],
            },
        ),
        migrations.CreateModel(
            name='SecurityCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=32)),
                ('stock_amount', models.IntegerField()),
                ('ipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_company_set', to='ipo.ipo')),
            ],
            options={
                'db_table': 'ipo_security_company',
                'ordering': ['-ipo'],
            },
        ),
    ]
