# Generated by Django 3.2 on 2021-05-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpoException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=32)),
                ('company_name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'ipo_exception',
            },
        ),
    ]
